version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-security-updates:
        dependency-type: development
        applies-to: security-updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-security-updates:
        applies-to: security-updates
